// Checks that every item from the old command sheet (command_sheet_v1_items.json) still appears in the
// Drafter Reference, and writes REFERENCE_INVENTORY.md: old item -> where it lives now.
// Exits non-zero if anything is unaccounted for.
const fs = require("fs");
const path = require("path");
const C = require("./reference_content");
const items = require("./command_sheet_v1_items.json");

// Deliberate changes: old item name -> explanation (kept here so the report shows them).
const DECISIONS = {
  "Cycle overlaps": "Replaced by selection cycling, CTRL+W (section 3), the documented method (SELECTIONCYCLING).",
};

const norm = (s) => s.toUpperCase().replace(/[^A-Z0-9'%#@.]+/g, " ");
const levelText = [["Cover", norm(JSON.stringify(C.COVER))], ...C.LEVELS.map((L) => [`Section ${L.n}`, norm(JSON.stringify(L))])];
const esc = (k) => k.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
const where = (key) => levelText.filter(([, txt]) => new RegExp(`(^|[^A-Z0-9])${esc(key)}([^A-Z0-9]|$)`).test(txt)).map(([n]) => n);

function keysFor(it) {
  const caps = (s) => (norm(s).match(/(?:^|\s)('?[A-Z][A-Z0-9-]{1,}|%%D|@|#\S+)(?=\s|$)/g) || []).map((x) => x.trim())
    .filter((x) => !["THE", "AND", "OR", "ON", "OFF", "TO", "OF", "IN", "A", "IS", "YES", "NO"].includes(x));
  if (/^Step by step/.test(it.section)) return caps(it.name).slice(0, 2);
  if (/^(Golden rules|First aid)/.test(it.section)) return caps(it.detail).slice(0, 3);
  if (/^(Troubleshooting|Warnings)/.test(it.section)) {
    const typed = (it.detail.match(/\*\*([^*]+)\*\*/g) || []).map((x) => norm(x.slice(2, -2)).trim().split(" ")[0]);
    return typed.length ? typed.slice(0, 1) : caps(it.name + " " + it.detail).slice(0, 2);
  }
  const k = caps(it.name);
  return k.length ? k : caps(it.detail).slice(0, 1);
}

const rows = [];
let missing = 0;
for (const it of items) {
  const keys = keysFor(it);
  const found = [...new Set(keys.flatMap(where))];
  const ok = found.length > 0 || DECISIONS[it.name];
  if (!ok) missing++;
  rows.push(`| ${it.section} | ${it.name.replace(/\|/g, "/")} | ${keys.join(", ") || "-"} | ${found.length ? found.join(", ") : DECISIONS[it.name] || "**NOT FOUND**"} |`);
}
const md = [
  "# Command Reference inventory",
  "",
  "Every item from the previous command sheet (`command_sheet_v1_items.json`, " + items.length + " items) and where it lives in the",
  "Survey CAD Command Reference. Generated by `check_inventory.js`; the build fails if an item has no home.",
  "",
  "| Old section | Item | Search keys | Now in |",
  "|---|---|---|---|",
  ...rows,
  "",
].join("\n");
fs.writeFileSync(path.join(__dirname, "REFERENCE_INVENTORY.md"), md);
console.log(`${items.length} items, ${missing} unaccounted for`);
if (missing) {
  for (const r of rows.filter((r) => r.includes("NOT FOUND"))) console.log(r);
  process.exit(1);
}
